#include<iostream.h>
#include<conio.h>
#include<iomanip.h>
void main()
{
int a;
clrscr();
cout<<"ENTER ROLL NO ";
cin>>a;
if (a==1)
cout<<"NAME= BUTGJF"<<endl<<"STS NO= 132476567869";
else if (a==2)
cout<<"NAME= DFIGJBJKG"<<endl<<"STS NO= 987654321";
else if (a==3)
cout<<"NAME= QWERTY"<<endl<<"STS NO= 1345689796";
else if (a==4)
cout<<"NAME= TREWQ"<<endl<<"STS NO= 8676452457";
else if (a==5)
cout<<"NAME= VGURHFTU"<<endl<<"STS NO= 789685674";
else if (a==6)
cout<<"NAME= GFUIRTUG"<<endl<<"STS NO= 7543535486";
else if (a==7)
cout<<"NAME= JTIUGKJG7U"<<endl<<"STS NO= 8563563265";
else if (a==8)
  cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 8245543246";
else if (a==9)
  cout<<"NAME= 8939826585"<<endl<<"STS NO= 0943286859";
  else if (a==10)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 8245543235";
  else if (a==11)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 8245534226";
  else if (a==12)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 8245531346";
  else if (a==13)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 824532745346";
  else if (a==14)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82423641346";
  else if (a==15)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82488561346";
  else if (a==16)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82414781346";
  else if (a==17)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82432531346";
  else if (a==18)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 85895531346";
  else if (a==19)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82258531346";
  else if (a==20)
    cout<<"NAME= VBGSYFEKI"<<endl<<"STS NO= 82455258346";
else
cout<<"STUDENT NOT FOUND ";
getch();
}
